# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coinjet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coinjet
    pod 'Alamofire', '~> 4.5'
    pod 'XLPagerTabStrip', '~> 8.0'
    pod 'SwiftyJSON'
    pod 'SnapKit', '~> 3.0.0'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'KakaoOpenSDK'

  target 'CoinjetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoinjetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
